analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: frontpage.country_name
  adjective: frontpage.country_adjective
create_goals:
  previous_next_links: true
  goal_content_heading: ''
  goals: []
create_indicators:
  previous_next_links: true
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: PoC
  message: ''
  hidden: false
email_contacts:
  questions: l-lantaron@eustat.eus
  suggestions: l-lantaron@eustat.eus
  functional: l-lantaron@eustat.eus
empty_metadata_placeholder: ''
empty_metadata_placeholder_sources: ''
environment: staging
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: https://x.com/eustat
    translation_key: general.twitter
  - path: https://www.facebook.com/eustat
    translation_key: general.facebook
  - path: https://www.youtube.com/user/eustat1986
    translation_key: general.youtube
  - path: https://es.linkedin.com/company/eustat
    translation_key: general.linkedin
  - path: https://www.eustat.eus/indice.html
    translation_key: general.website
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: orange
  - title: 'Sección 1: Lorem ipsum'
    content: >
      Descripción Sección 1: Lorem ipsum dolor sit amet, consectetur adipiscing
      elit. Morbi mollis

      cursus est sed dapibus.
    include: ''
    button_label: Read more
    button_link: https://example.com
    rule_color: blue
  - title: 'Sección 2: Nam vestibulum'
    content: >
      Descripción Sección 2: Nam vestibulum, purus quis porttitor imperdiet,
      nisl sem mollis nisl, a

      interdum risus enim vitae tortor. Donec feugiat accumsan rutrum.
    include: ''
    button_label: Read more
    button_link: https://example.com
    rule_color: orange
frontpage_goals_grid:
  title: frontpage.heading_short
  description: frontpage.instructions_shorter
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: /site3/assets/img/goals
goal_image_extension: ''
goals_page:
  title: general.goals
  description: frontpage.instructions_shorter
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header_language_toggle: links
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
ignored_disaggregations: []
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: map
  tab_2: chart
  tab_3: table
  tab_4: ''
languages:
  - es
  - eu
  - en
languages_public: []
logos:
  - language: es
    src: /assets/img/es/SDG_logo.png
    alt: Mi texto alternativo
  - language: eu
    src: /assets/img/eu/SDG_logo.png
    alt: Nire testu alterntiboa
  - language: en
    src: /assets/img/en/SDG_logo.png
    alt: My alternative Text
map_layers: []
map_options:
  disaggregation_controls: false
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: 5,5
menu:
  - path: /
    translation_key: general.home
    dropdown: []
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
meta_tags: []
news:
  category_links: true
observation_attributes: []
progress_status:
  status_heading: ''
  status_help: ''
  status_types: []
progressive_web_app:
  enabled: false
  name: ''
  short_name: ''
  precaching: false
proxy_indicators:
  label: ''
  description: ''
remote_data_prefix: https://lls-eustat.github.io/data3
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_indicator_count_label: ''
  disaggregation_tabs: true
  status_types:
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: https://github.com/LLS-Eustat/data3
repository_url_site: https://github.com/LLS-Eustat/site3
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
use_new_config_forms: true
validate_indicator_config: false
validate_site_config: false
x_axis_label: indicator.x_axis_label
