
# Configurar los datos de acceso a la cuenta de Google Analytics (hablar con Difusión)

analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates

# Hay que mirar que cumplimos con la normativa de Cookies, y quitar los avisos (hablar con Difusión)
cookie_consent_form:
  enabled: false

# Las referencias a Country, con translation key, para que aparezca en 3 idiomas. Solo aparecerá en los gráficos, he quitado toda referencia en el frontpage
country:
  name: general.pais
  adjective: general.adjetivo

# Crear botones de objetivo e indicador siguientes, y darles formato de color del indicador (estilos)
create_goals:
  previous_next_links: true
  goals: []
create_indicators:
  previous_next_links: true

create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: ''
  message: ''
  hidden: true
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
footer_language_toggle: none
footer_menu: []

# Modificamos los frontpage_cards 2 y 3 (OCECA y Lehendakaritza. Con translation keys. Analizar la mejor forma de incluir los iconos. 
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: '#a5a7a8'
  - title: frontpage.oceca_title
    content: frontpage.oceca_content
    include: ''
    rule_color: '#a5a7a8'
  - title: frontpage.lehendakaritza_title
    content: frontpage.lehendakaritza_content
    include: ''
    rule_color: '#a5a7a8'
frontpage_goals_grid:
  title: frontpage.heading_short
  description: frontpage.instructions_shorter
frontpage_introduction_banner: {}
goal_image_base: https://open-sdg.org/sdg-translations/assets/img/goals
goal_image_extension: ''
goals_page:
  title: general.goals
  description: frontpage.instructions_shorter
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: true
header_language_toggle: links
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''


# Los 3 idiomas
languages:
  - es
  - eu
  - en
languages_public: []
logos: []

# Añadimos 3 mapas. Hay que ver qué zoom se ajusta mejor a cada capa.
map_layers:
  - subfolder: Territorio
    label: Territorio
    min_zoom: 2
    max_zoom: 6
    staticBorders: true
  - subfolder: Comarca
    label: Comarca
    min_zoom: 7
    max_zoom: 8
    staticBorders: true
  - subfolder: Municipio
    label: Municipio
    min_zoom: 9
    max_zoom: 14
    staticBorders: true

# Analizar si se puede incluir la base de Geoeuskadi. Poner disaggregation_controls: true
map_options:
  disaggregation_controls: true
  minZoom: 5
  maxZoom: 14
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: ''
menu:
  - path: /
    translation_key: general.home
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
news:
  category_links: false


# Activar progress status y que aparezca en las páginas de goals y de indicators. Ver si es posible incluirlo como tab en el report (Informes)
progress_status:
  status_heading: ''
  status_help: ''
  status_types:
    - value: not_available
      label: status.progress_not_available
      image: assets/img/progress/not-available.png
      alt: status.progress_not_available
    - value: target_achieved
      label: status.progress_target_achieved
      image: assets/img/progress/target-achieved.png
      alt: status.progress_target_achieved
    - value: challenges_remain
      label: status.progress_challenges_remain
      image: assets/img/progress/challenges-remain.png
      alt: status.progress_challenges_remain
    - value: approaching_target
      label: status.progress_approaching_target
      image: assets/img/progress/approaching-target.png
      alt: status.progress_approaching_target
remote_data_prefix: https://uxuss.github.io/data
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: https://github.com/eustat-des/data
repository_url_site: https://github.com/eustat-des/site
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url

# Activamos el formulario nuevo para la configuración de la página, para hacer pruebas
use_new_config_forms: true
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
